---
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    ports: ['${DOCKER_MACHINE_IP}:9200:9200']
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_TAG}
    environment: ['ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}']
    ports: ['${DOCKER_MACHINE_IP}:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']
  mongo:
    image: mongo:${MONGO_TAG}
    ports: ['${DOCKER_MACHINE_IP}:27017:27017']
    networks: ['stack']
  fakesmtp:
    image: digiplant/fake-smtp
    ports: ['${DOCKER_MACHINE_IP}:1025:25']
    volumes: ['./email:/var/mail']

networks: {stack: {}}
